routes/web.php
<?php
/**
 * web.php
 * Copyright (c) 2019 james@firefly-iii.org.
 *
 * This file is part of Firefly III (https://github.com/firefly-iii).
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

declare(strict_types=1);

if (!defined('DATEFORMAT')) {
    define('DATEFORMAT', '(19|20)[0-9]{2}-?[0-9]{2}-?[0-9]{2}');
}

Route::group(
    [
        'namespace' => 'FireflyIII\Http\Controllers\System',
        'as'        => 'installer.',
        'prefix'    => 'install',
    ],
    static function (): void {
        Route::get('', ['uses' => 'InstallController@index', 'as' => 'index']);
        Route::post('runCommand', ['uses' => 'InstallController@runCommand', 'as' => 'runCommand']);
    }
);

Route::group(
    ['middleware' => 'binders-only', 'namespace' => 'FireflyIII\Http\Controllers\System', 'as' => 'cron.', 'prefix' => 'cron'],
    static function (): void {
        Route::get('run/{cliToken}', ['uses' => 'CronController@cron', 'as' => 'cron']);
    }
);

Route::group(
    ['middleware' => 'binders-only', 'namespace' => 'FireflyIII\Http\Controllers\System'],
    static function (): void {
        Route::get('offline', static fn () => view('errors.offline'));
        Route::get('health', ['uses' => 'HealthcheckController@check', 'as' => 'healthcheck']);
    }
);

// These routes only work when the user is NOT logged in.
Route::group(
    ['middleware' => 'user-not-logged-in', 'namespace' => 'FireflyIII\Http\Controllers'],
    static function (): void {
        // Authentication Routes...
        Route::get('login', ['uses' => 'Auth\LoginController@showLoginForm', 'as' => 'login']);
        Route::post('login', ['uses' => 'Auth\LoginController@login', 'as' => 'login.post']);

        // Registration Routes...
        Route::get('register', ['uses' => 'Auth\RegisterController@showRegistrationForm', 'as' => 'register']);
        Route::get('invitee/{code}', ['uses' => 'Auth\RegisterController@showInviteForm', 'as' => 'invite']);
        Route::post('register', 'Auth\RegisterController@register');

        // Password Reset Routes...
        Route::get('password/reset/{token}', ['uses' => 'Auth\ResetPasswordController@showResetForm', 'as' => 'password.reset']);
        Route::post('password/email', ['uses' => 'Auth\ForgotPasswordController@sendResetLinkEmail', 'as' => 'password.email']);
        Route::post('password/reset', ['uses' => 'Auth\ResetPasswordController@reset', 'as' => 'password.reset.post']);
        Route::get('password/reset', ['uses' => 'Auth\ForgotPasswordController@showLinkRequestForm', 'as' => 'password.reset.request']);

        // Change email routes:
        Route::get('profile/confirm-email-change/{token}', ['uses' => 'ProfileController@confirmEmailChange', 'as' => 'profile.confirm-email-change']);
        Route::get('profile/undo-email-change/{token}/{oldAddressHash}', ['uses' => 'ProfileController@undoEmailChange', 'as' => 'profile.undo-email-change']);
    }
);

// For some other routes, it is only relevant that the user is authenticated.
Route::group(
    ['middleware' => 'user-simple-auth', 'namespace' => 'FireflyIII\Http\Controllers'],
    static function (): void {
        Route::get('error', ['uses' => 'DebugController@displayError', 'as' => 'error']);
        Route::post('logout', ['uses' => 'Auth\LoginController@logout', 'as' => 'logout']);
        Route::get('flush', ['uses' => 'DebugController@flush', 'as' => 'flush']);
        // Route::get('routes', ['uses' => 'DebugController@routes', 'as' => 'routes']);
        Route::get('debug', 'DebugController@index')->name('debug');
    }
);

// For the two factor routes, the user must be logged in, but NOT 2FA. Account confirmation does not matter here.
Route::group(
    ['middleware' => 'user-logged-in-no-2fa', 'prefix' => 'two-factor', 'as' => 'two-factor.', 'namespace' => 'FireflyIII\Http\Controllers\Auth'],
    static function (): void {
        Route::post('submit', ['uses' => 'TwoFactorController@submitMFA', 'as' => 'submit']);
        Route::get('lost', ['uses' => 'TwoFactorController@lostTwoFactor', 'as' => 'lost']); // can be removed when v2 is live.
    }
);

// For all other routes, the user must be fully authenticated and have an activated account.

// Home Controller.
Route::group(
    ['middleware' => ['user-full-auth'], 'namespace' => 'FireflyIII\Http\Controllers'],
    static function (): void {
        Route::get('/', ['uses' => 'HomeController@index', 'as' => 'index']);
        Route::get('/flash', ['uses' => 'DebugController@testFlash', 'as' => 'test-flash']);
        Route::get('/home', ['uses' => 'HomeController@index', 'as' => 'home']);
        Route::post('/daterange', ['uses' => 'HomeController@dateRange', 'as' => 'daterange']);
    }
);

// show inactive

/*
 * Account Controller.
 * DROP ME WHEN v2 hits
 */
Route::group(
    ['middleware' => 'user-full-auth', 'namespace' => 'FireflyIII\Http\Controllers', 'prefix' => 'inactive-accounts', 'as' => 'accounts.'],
    static function (): void {
        Route::get('{objectType}', ['uses' => 'Account\IndexController@inactive', 'as' => 'inactive.index'])->where(
            'objectType',
            'revenue|asset|expense|liabilities'
        );
    }
);
Route::group(
    ['middleware' => 'user-full-auth', 'namespace' => 'FireflyIII\Http\Controllers', 'prefix' => 'accounts', 'as' => 'accounts.'],
    static function (): void {
        // show:
        Route::get('{objectType}', ['uses' => 'Account\IndexController@index', 'as' => 'index'])->where('objectType', 'revenue|asset|expense|liabilities');

        // create
        Route::get('create/{objectType}', ['uses' => 'Account\CreateController@create', 'as' => 'create'])->where(
            'objectType',
            'revenue|asset|expense|liabilities'
        );
        Route::post('store', ['uses' => 'Account\CreateController@store', 'as' => 'store']);

        // edit
        Route::get('edit/{account}', ['uses' => 'Account\EditController@edit', 'as' => 'edit']);
        Route::post('update/{account}', ['uses' => 'Account\EditController@update', 'as' => 'update']);

        // delete
        Route::get('delete/{account}', ['uses' => 'Account\DeleteController@delete', 'as' => 'delete']);
        Route::post('destroy/{account}', ['uses' => 'Account\DeleteController@destroy', 'as' => 'destroy']);

        // show
        Route::get('show/{account}/all', ['uses' => 'Account\ShowController@showAll', 'as' => 'show.all']);
        Route::get('show/{account}/{start_date?}/{end_date?}', ['uses' => 'Account\ShowController@show', 'as' => 'show'])
            ->where(['start_date' => DATEFORMAT])
            ->where(['end_date' => DATEFORMAT])
        ;

        // reconcile routes:
        Route::get('reconcile/{account}/index/{start_date?}/{end_date?}', ['uses' => 'Account\ReconcileController@reconcile', 'as' => 'reconcile'])
            ->where(['start_date' => DATEFORMAT])
            ->where(['end_date' => DATEFORMAT])
        ;
        Route::post('reconcile/{account}/submit/{start_date?}/{end_date?}', ['uses' => 'Account\ReconcileController@submit', 'as' => 'reconcile.submit'])
            ->where(['start_date' => DATEFORMAT])
            ->where(['end_date' => DATEFORMAT])
        ;

        // reconcile JSON routes
        Route::get('reconcile/{account}/overview/{start_date?}/{end_date?}', ['uses' => 'Json\ReconcileController@overview', 'as' => 'reconcile.overview'])
            ->where(['start_date' => DATEFORMAT])
            ->where(['end_date' => DATEFORMAT])
        ;
        Route::get(
            'reconcile/{account}/transactions/{start_date?}/{end_date?}',
            ['uses' => 'Json\ReconcileController@transactions', 'as' => 'reconcile.transactions']
        )
            ->where(['start_date' => DATEFORMAT])
            ->where(['end_date' => DATEFORMAT])
        ;
    }
);

// Attachment Controller.
Route::group(
    ['middleware' => 'user-full-auth', 'namespace' => 'FireflyIII\Http\Controllers', 'prefix' => 'attachments', 'as' => 'attachments.'],
    static function (): void {
        Route::get('', ['uses' => 'AttachmentController@index', 'as' => 'index']);
        Route::get('edit/{attachment}', ['uses' => 'AttachmentController@edit', 'as' => 'edit']);
        Route::get('delete/{attachment}', ['uses' => 'AttachmentController@delete', 'as' => 'delete']);
        Route::get('download/{attachment}', ['uses' => 'AttachmentController@download', 'as' => 'download']);
        Route::get('view/{attachment}', ['uses' => 'AttachmentController@view', 'as' => 'view']);

        Route::post('update/{attachment}', ['uses' => 'AttachmentController@update', 'as' => 'update']);
        Route::post('destroy/{attachment}', ['uses' => 'AttachmentController@destroy', 'as' => 'destroy']);
    }
);

// Bills Controller.
Route::group(
    ['middleware' => 'user-full-auth', 'namespace' => 'FireflyIII\Http\Controllers', 'prefix' => 'bills', 'as' => 'bills.'],
    static function (): void {
        Route::get('', ['uses' => 'Bill\IndexController@index', 'as' => 'index']);
        Route::post('rescan/{bill}', ['uses' => 'Bill\ShowController@rescan', 'as' => 'rescan']);
        Route::get('create', ['uses' => 'Bill\CreateController@create', 'as' => 'create']);
        Route::get('edit/{bill}', ['uses' => 'Bill\EditController@edit', 'as' => 'edit']);

resources/views/v2/partials/layout/breadcrumbs.blade.php
@if(count($breadcrumbs) > 0)
    <ol class="breadcrumb float-sm-end">
        @foreach ($breadcrumbs as $bc)
            @if($bc->url and !$loop->last)
                <li class="breadcrumb-item"><a href="{{ $bc->url }}">{{ $bc->title }}</a></li>
            @else
                <li class="breadcrumb-item active">{{ $bc->title }}</li>
            @endif
        @endforeach
    </ol>
@endif

resources/views/v2/partials/layout/footer.blade.php
<footer class="app-footer">
    <!--begin::To the end-->
    <div class="float-end d-none d-sm-inline">
        <a href="{{ route('debug') }}">v{{ $FF_VERSION }}</a>
    </div>
    <!--end::To the end-->
    <!--begin::Copyright-->
    <a href="https://github.com/firefly-iii/firefly-iii/">Firefly III</a> &copy; James Cole,
    <a href="https://github.com/firefly-iii/firefly-iii/blob/main/LICENSE">AGPL-3.0-or-later</a>
    <!--end::Copyright-->
</footer>

resources/views/v2/partials/layout/head.blade.php
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <base href="{{ route('index') }}/">
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <meta name="robots" content="noindex, nofollow, noarchive, noodp, NoImageIndex, noydir">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="color-scheme" content="light dark">

    <script type="text/javascript" nonce="{{ $JS_NONCE }}">
        /*!
 * Color mode toggler for Bootstrap's docs (https://getbootstrap.com/)
 * Copyright 2011-2023 The Bootstrap Authors
 * Licensed under the Creative Commons Attribution 3.0 Unported License.
 */

        (() => {
            'use strict'
            // todo store just happens to store in localStorage but if not, this would break.
            const getStoredTheme = () => JSON.parse(localStorage.getItem('darkMode'))

            const getPreferredTheme = () => {
                const storedTheme = getStoredTheme()
                if (storedTheme) {
                    return storedTheme
                }

                return window.matchMedia('(prefers-color-scheme: dark)').matches ? 'dark' : 'light'
            }

            const setTheme = theme => {
                if (theme === 'browser' && window.matchMedia('(prefers-color-scheme: dark)').matches) {
                    document.documentElement.setAttribute('data-bs-theme', 'dark')
                    window.theme = 'dark';
                    return;
                }
                if (theme === 'browser' && window.matchMedia('(prefers-color-scheme: light)').matches) {
                    window.theme = 'light';
                    document.documentElement.setAttribute('data-bs-theme', 'light')
                    return;
                }
                document.documentElement.setAttribute('data-bs-theme', theme)
                window.theme = theme;
            }

            setTheme(getPreferredTheme())

            window.matchMedia('(prefers-color-scheme: dark)').addEventListener('change', () => {
                const storedTheme = getStoredTheme()
                if (storedTheme !== 'light' && storedTheme !== 'dark') {
                    setTheme(getPreferredTheme())
                }
            })
        })()
    </script>

    <title>
        @if($subTitle)
            {{ $subTitle }} »
        @endif

        @if($title !== 'Firefly III')
            {{ $title }} »
        @endif
        Firefly III
    </title>

    <!--begin::Primary Meta Tags-->
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!--begin::Fonts-->
    <link href="v2/css/fonts.css" rel="stylesheet">
    <!--end::Fonts-->

    <!--begin::Required Plugin(AdminLTE)-->
    <link rel="stylesheet" href="v2/css/adminlte.css">
    <!--end::Required Plugin(AdminLTE)-->
    @yield('vite')

</head>

resources/views/v2/partials/layout/scripts.blade.php
<!--begin::Required Plugin(AdminLTE)-->
<script src="v2/js/adminlte.js" nonce="{{ $JS_NONCE }}"></script>
<!--end::Required Plugin(AdminLTE)-->

resources/views/v2/partials/layout/sidebar.blade.php
<aside class="app-sidebar bg-body-secondary shadow" data-bs-theme="dark">
    <!--begin::Sidebar Brand-->
    <div class="sidebar-brand">
        <!--begin::Brand Link-->
        <a href="{{route('index') }}" class="brand-link">
            <!--begin::Brand Image-->
            <img src="v2/i/logo.png" alt="Firefly III Logo"
                 class="brand-image opacity-75 shadow">
            <!--end::Brand Image-->
            <!--begin::Brand Text-->
            <span class="brand-text fw-light">Firefly III</span>
            <!--end::Brand Text-->
        </a>
        <!--end::Brand Link-->
    </div>
    <!--end::Sidebar Brand-->
    <!--begin::Sidebar Wrapper-->

    <div class="sidebar-wrapper">
        <nav class="mt-2">
            <!--begin::Sidebar Menu-->
            <ul class="nav sidebar-menu flex-column" data-lte-toggle="treeview" role="menu"
                data-accordion="false">
                <li class="nav-item menu-open">
                    <a href="{{ route('index') }}" class="nav-link active">
                        <em class="nav-icon fa-solid fa-gauge-high"></em>
                        <p>
                            {{ __('firefly.dashboard')  }}
                        </p>
                    </a>
                </li>
                <li class="nav-header">{{ strtoupper(__('firefly.financial_control'))  }}</li>
                <li class="nav-item">
                    <a href="{{ route('budgets.index')  }}" class="nav-link">
                        <em class="nav-icon fa-solid fa-chart-pie"></em>
                        <p>{{ __('firefly.budgets')  }}</p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{{ route('subscriptions.index') }}" class="nav-link">
                        <i class="nav-icon fa-regular fa-calendar"></i>
                        <p>{{ __('firefly.subscriptions')  }}</p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{{ route('piggy-banks.index') }}" class="nav-link">
                        <em class="nav-icon fa-solid fa-piggy-bank"></em>
                        <p>{{ __('firefly.piggy_banks')  }}</p>
                    </a>
                </li>
                <li class="nav-header">{{ strtoupper(__('firefly.accounting'))  }}</li>
                <li class="nav-item">
                    <a href="#" class="nav-link">
                        <em class="nav-icon fa-solid fa-arrow-right-arrow-left"></em>
                        <p>
                            {{ __('firefly.transactions') }}
                            <i class="nav-arrow fa-solid fa-chevron-right"></i>
                        </p>
                    </a>
                    <ul class="nav nav-treeview">
                        <li class="nav-item">
                            <a href="{{ route('transactions.index',['withdrawal']) }}" class="nav-link">
                                <em class="nav-icon fa-solid fa-arrow-left"></em>
                                <p>{{ __('firefly.expenses')  }}</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="{{ route('transactions.index', ['deposit']) }}" class="nav-link">
                                <em class="nav-icon fa-solid fa-arrow-right"></em>
                                <p>{{ __('firefly.income') }}</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="{{ route('transactions.index', ['transfers']) }}" class="nav-link">
                                <i class="nav-icon fa-solid fa-arrows-rotate"></i>
                                <p>{{ __('firefly.transfers') }}</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="{{ route('transactions.index', ['all']) }}" class="nav-link">
                                <i class="nav-icon fa-solid fa-arrows-turn-to-dots"></i>
                                <p>{{ __('firefly.all_transactions') }}</p>
                            </a>
                        </li>
                    </ul>
                </li>
                <li class="nav-item">
                    <a href="#" class="nav-link">
                        <i class="nav-icon fa-solid fa-microchip"></i>
                        <p>
                            {{ __('firefly.automation') }}
                            <i class="nav-arrow fa-solid fa-chevron-right"></i>
                        </p>
                    </a>
                    <ul class="nav nav-treeview">
                        <li class="nav-item">
                            <a href="{{ route('rules.index') }}" class="nav-link">
                                <i class="nav-icon fa-solid fa-shuffle"></i>
                                <p>{{ __('firefly.rules') }}</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="{{ route('recurring.index') }}" class="nav-link">
                                <i class="nav-icon fa-solid fa-repeat"></i>
                                <p>{{ __('firefly.recurrences') }}</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="{{ route('webhooks.index') }}" class="nav-link">
                                <i class="nav-icon fa-solid fa-bolt-lightning"></i>
                                <p>{{ __('firefly.webhooks') }}</p>
                            </a>
                        </li>
                    </ul>
                </li>
                <li class="nav-header">{{ strtoupper(__('firefly.others'))  }}</li>
                <li class="nav-item">
                    <a href="#" class="nav-link">
                        <i class="nav-icon fa-regular fa-credit-card"></i>
                        <p>
                            {{ __('firefly.accounts') }}
                            <i class="nav-arrow fa-solid fa-chevron-right"></i>
                        </p>
                    </a>
                    <ul class="nav nav-treeview">
                        <li class="nav-item">
                            <a href="{{ route('accounts.index', ['asset']) }}" class="nav-link">
                                <i class="nav-icon fa-solid fa-money-bills"></i>
                                <p>{{ __('firefly.asset_accounts') }}</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="{{ route('accounts.index', ['expense']) }}" class="nav-link">
                                <i class="nav-icon fa-solid fa-cart-shopping"></i>
                                <p>{{ __('firefly.expense_accounts') }}</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="{{ route('accounts.index', ['revenue']) }}" class="nav-link">
                                <i class="nav-icon fa-solid fa-money-bill-trend-up"></i>
                                <p>{{ __('firefly.revenue_accounts') }}</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="{{ route('accounts.index', ['liabilities']) }}" class="nav-link">
                                <i class="nav-icon fa-solid fa-landmark"></i>
                                <p>{{ __('firefly.liabilities') }}</p>
                            </a>
                        </li>
                    </ul>
                </li>
                <li class="nav-item">
                    <a href="#" class="nav-link">
                        <i class="nav-icon fa-solid fa-tags"></i>
                        <p>
                            {{ __('firefly.classification') }}
                            <i class="nav-arrow fa-solid fa-chevron-right"></i>
                        </p>
                    </a>
                    <ul class="nav nav-treeview">
                        <li class="nav-item">
                            <a href="{{ route('categories.index') }}" class="nav-link">
                                <i class="nav-icon fa-regular fa-bookmark"></i>
                                <p>{{ __('firefly.categories') }}</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="{{ route('tags.index') }}" class="nav-link">
                                <i class="nav-icon fa-solid fa-tag"></i>
                                <p>{{ __('firefly.tags') }}</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="{{ route('object-groups.index') }}" class="nav-link">
                                <i class="nav-icon fa-regular fa-envelope"></i>
                                <p>{{ __('firefly.object_groups') }}</p>
                            </a>
                        </li>
                    </ul>
                </li>

                <li class="nav-item">
                    <a href="{{ route('reports.index') }}" class="nav-link">
                        <i class="nav-icon fa-solid fa-chart-column"></i>
                        <p>{{ __('firefly.reports') }}</p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{{ route('export.index') }}" class="nav-link">
                        <i class="nav-icon fa-solid fa-upload"></i>
                        <p>{{ __('firefly.export_data_menu') }}</p>
                    </a>
                </li>

                <li class="nav-item">
                    <a href="{{ route('logout') }}" class="nav-link logout-link">
                        <i class="nav-icon fa-solid fa-arrow-right-from-bracket"></i>
                        <p>TODO {{ __('firefly.logout') }}</p>
                    </a>
                </li>
            </ul>
            <!--end::Sidebar Menu-->
        </nav>
    </div>
    <!--end::Sidebar Wrapper-->
</aside>

<!-- simple script for logout thing -->

resources/views/v2/partials/layout/topbar.blade.php
<li class="nav-item dropdown">
    <a class="nav-link" data-bs-toggle="dropdown" href="#">
        <i class="fa-solid fa-gears"></i>
    </a>
    <div class="dropdown-menu dropdown-menu-lg dropdown-menu-end">
        <a href="{{ route('admin.index') }}" class="dropdown-item">
            <em class="fa-regular fa-user me-2 fa-fw"></em>
            {{ __('firefly.system_settings') }}
        </a>
        <div class="dropdown-divider"></div>
        <a href="{{ route('currencies.index') }}" class="dropdown-item">
            <em class="fa-solid fa-euro-sign me-2 fa-fw"></em>
            {{ __('firefly.currencies') }}
        </a>
    </div>
</li>
<li class="nav-item dropdown">
    <a class="nav-link" data-bs-toggle="dropdown" href="#">
        <i class="fa-solid fa-user"></i>
    </a>
    <div class="dropdown-menu dropdown-menu-lg dropdown-menu-end">
        <span class="dropdown-item dropdown-header">{{ auth()->user()->email }}</span>
        <div class="dropdown-divider"></div>
        <a href="{{ route('profile.index') }}" class="dropdown-item">
            <em class="fa-regular fa-user me-2"></em>
            {{ __('firefly.profile') }}
        </a>
        <div class="dropdown-divider"></div>
        <a href="{{ route('preferences.index') }}" class="dropdown-item">
            <em class="fa-solid fa-user-gear me-2"></em>
            {{ __('firefly.preferences') }}
        </a>
        <div class="dropdown-divider"></div>
        <a href="#" class="dropdown-item">
            <em class="fa-solid fa-money-bill-transfer me-2"></em>
            TODO {{ __('firefly.administrations_index_menu') }}
        </a>
    </div>
</li>
<li class="nav-item dropdown">
    <a class="nav-link" data-bs-toggle="dropdown" href="#">
        <i class="fa-solid fa-plus-circle"></i>
    </a>
    <div class="dropdown-menu dropdown-menu-lg dropdown-menu-end">
        <!-- withdrawal, deposit, transfer -->
        <a href="{{ route('transactions.create', ['withdrawal']) }}" class="dropdown-item">
            <em class="fa-solid fa-arrow-left fa-fw me-2"></em>
            {{ __('firefly.create_new_withdrawal') }}
        </a>
        <a href="{{ route('transactions.create', ['deposit']) }}" class="dropdown-item">
            <em class="fa-solid fa-arrow-right fa-fw me-2"></em>
            {{ __('firefly.create_new_deposit') }}
        </a>
        <a href="{{ route('transactions.create', ['transfer']) }}" class="dropdown-item">
            <em class="fa-solid fa-arrows-rotate fa-fw me-2"></em>
            {{ __('firefly.create_new_transfer') }}
        </a>
        <div class="dropdown-divider"></div>

        <!-- asset, liability -->
        <a href="{{ route('accounts.create', ['asset']) }}" class="dropdown-item">
            <em class="fa-solid fa-money-bills fa-fw me-2"></em>
            {{ __('firefly.create_new_asset') }}
        </a>
        <a href="{{ route('accounts.create', ['liabilities']) }}" class="dropdown-item">
            <em class="fa-solid fa-landmark fa-fw me-2"></em>
            {{ __('firefly.create_new_liabilities') }}
        </a>
        <div class="dropdown-divider"></div>

        <!-- budget, category, piggy -->
        <a href="{{ route('budgets.create') }}" class="dropdown-item">
            <em class="fa-solid fa-pie-chart fa-fw me-2"></em>
            {{ __('firefly.create_new_budget') }}
        </a>
        <a href="{{ route('categories.create') }}" class="dropdown-item">
            <em class="fa-regular fa-bookmark fa-fw me-2"></em>
            {{ __('firefly.create_new_category') }}
        </a>
        <a href="{{ route('piggy-banks.create') }}" class="dropdown-item">
            <em class="fa-solid fa-piggy-bank fa-fw me-2"></em>
            {{ __('firefly.create_new_piggy_bank') }}
        </a>
        <div class="dropdown-divider"></div>

        <!-- contract, rule, recurring -->
        <a href="{{ route('subscriptions.create') }}" class="dropdown-item">
            <em class="fa-regular fa-calendar fa-fw me-2"></em>
            {{ __('firefly.create_new_subscription') }}
        </a>
        <a href="{{ route('rules.create') }}" class="dropdown-item">
            <em class="fa-solid fa-shuffle fa-fw me-2"></em>
            {{ __('firefly.create_new_rule') }}
        </a>
        <a href="{{ route('recurring.create') }}" class="dropdown-item">
            <em class="fa-solid fa-repeat fa-fw me-2"></em>
            {{ __('firefly.create_new_recurrence') }}
        </a>
        <a href="{{ route('webhooks.create') }}" class="dropdown-item">
            <em class="fa-solid fa-bolt-lightning fa-fw me-2"></em>
            {{ __('firefly.create_new_webhook') }}
        </a>
    </div>
</li>